apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prtb-zxfsw-leonel-edit
  namespace: p-hjpcq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-p4cw4
