apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-local-leonel-projectowner
  namespace: local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-owner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-p4cw4
